#!/usr/bin/env bash

function profile {
  local shome="${_scala_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  export SCALA_HOME="$shome/vendor/scala"
  PATH="$shome/bin:$SCALA_HOME/bin:$PATH"
}

profile
